name: 'dbt_deathmetal'
version: '1.0.0'
config-version: 2

profile: "{{ 'dbt_deathmetal_bq' if env_var('DBT_USE_BIGQUERY', 'false') == 'true' else 'dbt_deathmetal' }}"

model-paths: [ "models" ]
analysis-paths: [ "analyses" ]
test-paths: [ "tests" ]
seed-paths: [ "seeds" ]
macro-paths: [ "macros" ]
snapshot-paths: [ "snapshots" ]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  current_year: 2024
  analysis_start_year: 1980
  analysis_end_year: 2024
  
  environment: "{{ 'prod' if target.name == 'prod' else 'dev' }}"
  
  use_clustering: "{{ true if target.type == 'bigquery' else false }}"
  use_partitioning: "{{ true if target.type == 'bigquery' else false }}"
  batch_size: "{{ 50000 if target.type == 'bigquery' else 10000 }}"
  
  dataset_location: "{{ env_var('DBT_BIGQUERY_LOCATION', 'US') }}"
  job_timeout_ms: "{{ 600000 if target.name == 'prod' else 300000 }}"
  
  freshness_threshold_hours: "{{ 48 if target.name == 'prod' else 168 }}"
  test_severity: "{{ 'error' if target.name == 'prod' else 'warn' }}"

models:
  dbt_deathmetal:
    staging:
      +materialized: table
      +docs:
        node_color: "#228B22"

    intermediate:
      +materialized: "{{ 'table' if target.name == 'prod' else 'view' }}"
      +docs:
        node_color: "#FFA500"

    marts:
      +docs:
        node_color: "#4169E1"
      
      core:
        +materialized: table

      analytics:
        +materialized: "{{ 'table' if target.name == 'prod' else 'view' }}"


tests:
  dbt_deathmetal:
    +store_failures: true
    +schema: "{{ 'test_failures' if target.type == 'bigquery' else 'main' }}"

snapshots:
  dbt_deathmetal:
    +target_schema: "{{ 'snapshots' if target.type == 'bigquery' else 'main' }}"
    +strategy: timestamp
    +updated_at: updated_at

