[destination.duckdb.credentials]
database = "./death_metal.duckdb"

[sources.readers._read_csv.credentials]
aws_access_key_id = "admin"
aws_secret_access_key = "password123"
endpoint_url = "http://localhost:9000"
region_name = "us-east-1"

[sources.readers.filesystem.credentials]
aws_access_key_id = "admin"
aws_secret_access_key = "password123"
endpoint_url = "http://localhost:9000"
region_name = "us-east-1"

[sources.filesystem.credentials]
aws_access_key_id = "admin"
aws_secret_access_key = "password123"
endpoint_url = "http://localhost:9000"
region_name = "us-east-1"