[destination.bigquery.credentials]
location = "/home/user/.config/gcloud/dw-bigquery-462900-a4b8c80ac45d.json"

[sources.filesystem.credentials]
location = "/home/user/.config/gcloud/dw-bigquery-462900-a4b8c80ac45d.json"
